name: flux_virtual
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.3+9

environment:
  sdk: ^3.11.4


dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1  
  remixicon: ^1.4.1
  flag: ^7.0.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3
  http: ^1.2.1
  webview_flutter: ^4.7.0
  url_launcher: ^6.3.0
  flutter_contacts: ^2.2.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  flutter_launcher_icons: ^0.14.4
  in_app_review: ^2.0.9
  change_app_package_name: ^1.5.0
  firebase_remote_config: ^5.0.0
  audioplayers: ^6.8.0
  twilio_voice: ^0.3.2+2


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/Flux.png"  




flutter:

  
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/sounds/

  